// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3oPtJ-l3sUIC9LFwByxovRvy-WucFeDQ',
    appId: '1:370640896537:web:7ab19982a6349bd90da088',
    messagingSenderId: '370640896537',
    projectId: 'grapproj',
    authDomain: 'grapproj.firebaseapp.com',
    storageBucket: 'grapproj.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASUbSISjJ-KZpC9pt_Q3mJcaYhCg1VjBU',
    appId: '1:370640896537:android:acdd4946093550a40da088',
    messagingSenderId: '370640896537',
    projectId: 'grapproj',
    storageBucket: 'grapproj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJqJuXMqrZeFQeQLxi9s23h7U27gLT1Yw',
    appId: '1:370640896537:ios:e74ba6f392d768ba0da088',
    messagingSenderId: '370640896537',
    projectId: 'grapproj',
    storageBucket: 'grapproj.firebasestorage.app',
    iosBundleId: 'com.example.act12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJqJuXMqrZeFQeQLxi9s23h7U27gLT1Yw',
    appId: '1:370640896537:ios:e74ba6f392d768ba0da088',
    messagingSenderId: '370640896537',
    projectId: 'grapproj',
    storageBucket: 'grapproj.firebasestorage.app',
    iosBundleId: 'com.example.act12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3oPtJ-l3sUIC9LFwByxovRvy-WucFeDQ',
    appId: '1:370640896537:web:637867fac496cbbe0da088',
    messagingSenderId: '370640896537',
    projectId: 'grapproj',
    authDomain: 'grapproj.firebaseapp.com',
    storageBucket: 'grapproj.firebasestorage.app',
  );
}
